theme: jekyll-theme-minimal
title: "miqg"
description: "Hey there! I am a biotechnologist specialized in systems biology passionate about exploiting data for better understanding of our surroundings. I created this blog with the intention of sharing and keeping track of how I solved certain problems while "
