---
title: "howto-explore_kegg_KEGGgraph"
output: 
    html_document:
        code_folding: hide
        highlight: tango
        number_sections: false
        toc: true
        toc_float:
            collapsed: false
            smooth_scroll: true
        toc_depth: 3
        theme: flatly
---
# installation
```{r}
# BiocManager::install("KEGGgraph")
# BiocManager::install("KEGGREST")
```

# usage
```{r}
require(KEGGgraph)
```

```{r}
# download KGML files
require(KEGGREST)
require(doParallel)

nCores = 6

organism = 'hsa'
# pIds = ls(KEGGPATHID2NAME)[1:5]
pIds = gsub('path:hsa','', 
            names(keggList(database = 'pathway', organism = organism)))[1:5]
dbDir = '~/scratch/databases/kegg'
pathIdFile = paste0(organism, pIds, '.xml')
downloadFileNames = file.path(dbDir,pathIdFile)

registerDoParallel(nCores)
foreach (i = 1:length(pIds)) %dopar% {
    retrieveKGML(pIds[i], organism = organism, destfile = downloadFileNames[i], method="wget", quiet=TRUE)
}
```

```{r}
# load KGML pathways as graphs
keggFiles = list.files(dbDir, full.names=TRUE)
keggPathways = lapply(keggFiles, 
                      parseKGML2Graph, expandGenes=TRUE, genesOnly=TRUE)
names(keggPathways) = gsub('.xml','',basename(keggFiles))
```

```{r}
edges(keggPathways$hsa00010)
nodes(keggPathways$hsa00010)
```

